export const data = {
  title: 'Регистрация',
  fields: [
    {
      field: 'Email',
      name: 'email',
      type: 'email',
      max: '30',
      min: '2',
      required: 'required',
      autofocus: 'autofocus',
    },
    {
      field: 'Login',
      name: 'login',
      type: 'text',
      max: '30',
      min: '2',
      required: 'required',
      autofocus: 'autofocus',
    },
    {
      field: 'Name',
      name: 'first_name',
      type: 'text',
      max: '30',
      min: '2',
      required: 'required',
      autofocus: 'autofocus',
    },
    {
      field: 'Nickname',
      name: 'second_name',
      type: 'text',
      max: '30',
      min: '2',
      required: 'required',
      autofocus: 'autofocus',
    },
    {
      field: 'Phone',
      name: 'phone',
      type: 'phone',
      max: '30',
      min: '2',
      required: 'required',
      autofocus: 'autofocus',
    },
    {
      field: 'Password',
      name: 'password',
      type: 'password',
      max: '30',
      min: '2',
      required: 'required',
      autofocus: 'autofocus',
    },
    {
      field: 'Password',
      name: 'password',
      type: 'password',
      max: '30',
      min: '2',
      required: 'required',
      autofocus: 'autofocus',
    },
  ],

  button: 'Зарегистрироваться',
  classButton: 'form__button',
  classAvatar: 'form__avatar',
  text: 'Войти',
};
